name: pull request
on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'
      - name: Install Requirements
        run:
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=src" >> $GITHUB_ENV
      - name: Pylint
        run:
          pylint --fail-under=8 $(git ls-files '**/*.py')
      - name: Black
        run:
          black --check ./
      - name: Type Check (mypy)
        run: mypy src --strict
